require "fubelts.data-updates"
require "fufusion.data-updates"
require "fuweapon.data-updates"
require "fuoil.data-updates"
require "futrain.data-updates"
require "fudrill.data-updates"
require "fuconstruction.data-updates"
require "fuinserter.data-updates"